### ISSUE TITLE
JN 7 → tqdm_notebook(leave=False) → Error displaying widget: model not found

### ISSUE THREAD

**Issue by MichalRIcar** [jupyter-widgets/ipywidgets#3812]
Hi,

This message appears only in Jupyter Notebook 7 (not in JN<7) and obviously comes from the fact that tqdm widget is discarded by param "leave=False".

The Jupyter Notebook 7 together with the very last versions of packages (all installed on 27.7.2023) and so far everything works smoothly, however, a minor bug is when using tqdm_notebook(leave=False) inside another widget then in JN is reported "Error displaying widget: model not found".

The code logic is as follows:

```
from   ipywidgets         import interactive
from   tqdm.notebook      import tqdm_notebook

def x():
    for i in tqdm_notebook(['a'], leave=False):
        1

interactive(x)
```
![image](https://github.com/jupyter-widgets/ipywidgets/assets/62614119/0a064d1a-f052-431a-8d40-fb1eb1f74ef9)

I have reported the issue to tqdm and JN teams too.

Best,
Michal

**Comment by mwcraig** [comment]
@MichalRIcar -- thanks for opening the issue! It looks like this may have been addressed in tqdm v4.64.1: https://github.com/tqdm/tqdm/issues/1364.

We'd recommend upgrading and/or checking the version of tqdm; for now we are closing this issue.

**Comment by MichalRIcar** [comment]
@mwcraig, thank you, my version of tqdm is 4.65.0, yet the issue is there..

**Comment by MichalRIcar** [comment]
the issue persists on Jupyter Notebook 7 and JupyterLab 4.0.3, thus, very last versions 
![image](https://github.com/jupyter-widgets/ipywidgets/assets/62614119/81bb6433-365f-43f6-bd66-dfc965e2a44a)

**Comment by MichalRIcar** [comment]
As can be seen by just run code

![image](https://github.com/jupyter-widgets/ipywidgets/assets/62614119/4cedc1c0-8867-4edb-ab8c-2545868fe89f)

**Comment by RKwork85** [comment]
+1 The problem needs to be solved

**Comment by balopat** [comment]
+1 this is still an issue

**Comment by rarkoshipbob** [comment]
+1 still seeing this issue

python -m jupyter --version
Selected Jupyter core packages...
IPython          : 8.30.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.2.6
nbclient         : 0.10.1
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.2
qtconsole        : not installed
traitlets        : 5.14.3

**Comment by leopoldmarx** [comment]
+1 Any further updates?

**Comment by Seqaeon** [comment]
Still an issue
